### PR TITLE
Added the ability for vsm.doc_term_matrix to take an existing vocabulary

### PR DESCRIPTION
**Pull request by kyocum**
## Description
Added an additional vocabulary argument, same form as returned dictionary idtoterm.     Note that idtoterm is now an OrderedDict.

If vocabulary exists, rebuild stringstore from vocabulary, and create a test lambda to see if term exists in stringstore (now our vocabulary).    When creating the sparse matrix, make sure that it has the same shape as the vocabulary. 

Finally, if we have a vocabulary, don't bother trying to filter out the terms.  

## Motivation and Context

We want to be able to use Textacy / SpaCy to tokenize/lemmatize and build topic models.   We also would like to apply our trained topic model to new text.    However, the current form of doc_term_matrix does not take in an existing vocabulary -- it always makes a new one.   This PR allows doc_term_matrix to take in a prior vocabulary and use it to create the doc_term_matrix so that a trained topic model can successfully embed new text. 

[Issue 69](https://github.com/chartbeat-labs/textacy/issues/69)

## How Has This Been Tested?

Ran textacy tests before / after.   A bunch of tests already fail in master, and no new tests failed.  
The change should be transparent to existing functionality, but we need to add a separate test for this functionality. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code mostly follows the code style of this project.
- [ ] My change requires a change to the documentation, and I have updated it accordingly.

### CODE REVIEW

**Comment by bdewilde** [comment]
Hey @kyocum , thanks for the PR! Fixing this issue with the topic modeling workflow was my next big to-do, so your timing is perfect. 🙂  Please give me a few days to think on these changes — your solution seems fine, but I've been wondering if a more substantial refactor would be better in the long run. Thanks in advance for your patience!

**Comment by bdewilde** [comment]
Okay, I've committed into a branch an initial version of the "more substantial refactor" I mentioned, check it out [here[(https://github.com/chartbeat-labs/textacy/blob/vectorizer/textacy/vsm.py#L20).

Does this seem like a good (or _better_) option to you? Honestly, I'd love some user feedback! 🙂

**Comment by kyocum** [comment]
@bdewilde I think having a Vectorizer class that doesn't convolve parsing / tokenization with vocabulary building / usage is great!   Also want to be able to save / restore that Vectorizer in a similar fashion.    And, I also ignored any issues with weighting from the original vocabulary.   There's enough code in the new path, though, that having a bunch of tests might be useful.    I also saw that binarize at line 296 sets all entries in the doc_term_matrix to 1, but if you're using an existing vocabulary, would that still be right policy?   It may be that CSR fill does the right thing even if the dimensions are greater than the set items per row, but I wasn't sure.

**Comment by bdewilde** [comment]
Hey, glad you think the `Vectorizer` class is a good idea! I'll polish it up and add some tests soon. :+1:

Could you explain your concerns about binarization a bit more? I'm confused — everything in the `_reweight_values()` method occurs independent of the vocabulary. Right?

**Comment by kyocum** [comment]
Sorry, I just took a cursory glance; I'll look at it in more detail in the next day or so.  I'm on vacation so I'm in and out of contact.     

I also had a couple of other thoughts -- you may well have already taken care of this so apologies in advance!   They are around unexpected changes to the state of the Vectorizer.   The first is that I saw some code for re-indexing the vocab.   I think this is fine as long as it is always done in the context of a "fit" operation.   Otherwise it could result in a copy of the vocab index floating around outside the class that becomes unexpectedly out of date.   The second was to make sure that transform never unexpectedly extends the vocabulary: i.e., fit makes new vocab / transform uses it.   Like I said above, my apologies for being lazy -- I just wanted to get your ideas on these.   Thanks!

**Comment by bdewilde** [comment]
I _think_ I've taken care to handle those cases properly, but will probably want a second pair of eyes. Mind if I close this PR, then tag you on the one I'll open for the `Vectorizer`?

**Comment by kyocum** [comment]
Sounds good!

**Comment by bdewilde** [comment]
That was a bug ;) The correct call is actually `doc_term_matrix.data.fill(1)`. I'll close this out — the `Vectorizer` PR is open!

**Pull request closed without merging**
