### PR TITLE
Add MANIFEST.in file to include docs, tests and dist files

### PR DESCRIPTION
**Pull request by rolando**
Adds MANIFEST.in file to include docs, tests and distribution files (README, CHANGELOG, LICENSE) into the source distribution.

## Motivation and Context

It's a good practice to include docs, tests and license files in the source distribution.

## How Has This Been Tested?

It doesn't break the `sdist` or `build` command.

## Screenshots (if appropriate):

The changes in the source distribution before and after this patch is applied:

```diff
--- dist-log	2017-03-04 15:44:30.000000000 -0300
+++ dist-log2	2017-03-04 15:49:54.000000000 -0300
@@ -1,8 +1,37 @@
 x textacy-0.3.3/
+x textacy-0.3.3/CHANGELOG.rst
+x textacy-0.3.3/docs/
+x textacy-0.3.3/docs/Makefile
+x textacy-0.3.3/docs/source/
+x textacy-0.3.3/docs/source/api_reference.rst
+x textacy-0.3.3/docs/source/conf.py
+x textacy-0.3.3/docs/source/index.rst
+x textacy-0.3.3/docs/source/license.rst
+x textacy-0.3.3/LICENSE.txt
+x textacy-0.3.3/MANIFEST.in
 x textacy-0.3.3/PKG-INFO
 x textacy-0.3.3/README.rst
 x textacy-0.3.3/setup.cfg
 x textacy-0.3.3/setup.py
+x textacy-0.3.3/tests/
+x textacy-0.3.3/tests/test_capitolwords.py
+x textacy-0.3.3/tests/test_constants.py
+x textacy-0.3.3/tests/test_corpora_reddit_reader.py
+x textacy-0.3.3/tests/test_corpora_wiki_reader.py
+x textacy-0.3.3/tests/test_data.py
+x textacy-0.3.3/tests/test_export.py
+x textacy-0.3.3/tests/test_extract.py
+x textacy-0.3.3/tests/test_fileio.py
+x textacy-0.3.3/tests/test_keyterms.py
+x textacy-0.3.3/tests/test_preprocess.py
+x textacy-0.3.3/tests/test_readme.py
+x textacy-0.3.3/tests/test_similarity.py
+x textacy-0.3.3/tests/test_spacy_utils.py
+x textacy-0.3.3/tests/test_supremecourt.py
+x textacy-0.3.3/tests/test_text_stats.py
+x textacy-0.3.3/tests/test_text_utils.py
+x textacy-0.3.3/tests/test_topic_model.py
+x textacy-0.3.3/tests/test_vsm.py
 x textacy-0.3.3/textacy/
 x textacy-0.3.3/textacy/__init__.py
 x textacy-0.3.3/textacy/compat.py
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation, and I have updated it accordingly.

### CODE REVIEW

**Comment by bdewilde** [comment]
Hey @rolando , thanks for the PR! The reasoning makes sense, and the results look good.

I have one minor concern: Would `graft docs` include everything under the `docs/build` directory (generated via `docs/Makefile`), and if so, would it be advisable to include those build files? I think _no_, but I'm not 100% sure. If we don't want build files included in the source distribution, I guess we'd want to add `prune docs/build`...? Let me know what you think, I've never made a `MANIFEST.in` file before. 🙂 

Thanks in advance!

**Comment by rolando** [comment]
Right, makes sense to prune `docs/build`. Usually it's recommended to do a `sdist` from a clean directory, but mistakes happen.

Btw, I'm also working on a `textacy` conda's recipe in `conda-forge`: https://github.com/conda-forge/staged-recipes/pull/2455

**Comment by bdewilde** [comment]
Awesome. :shipit: 

I never got into the conda ecosystem, so am not familiar with how forge or recipes work. It makes it easier to get `textacy` and all its deps installed? At the very least, please let me know if there's anything you need from me to facilitate that process!

**Comment by rolando** [comment]
@bdewilde IIRC, I think tests are a weak point in the current recipe. It doesn't run tests because takes a long time due to having to download data files. It would be great to have a flag to turn-off auto-downloading and skip tests where the required corpora is not available.

**Comment by bdewilde** [comment]
Hey @rolando , I just committed changes so that the test cases for CapitolWords and SupremeCourt corpora are skipped unless the files have already been downloaded from S3. Let me know if that helps!

**Pull request merged**
